storage_mode: file  # or 'mysql' based on your choice

mysql:
  host: localhost
  port: 3306
  database: koth_tokens
  username: your_mysql_username
  password: your_mysql_password

file_storage:
  directory: data  # Folder where data files will be saved
  file_name: saveddata.dat  # File where player tokens are saved
