name: KothToken
version: v1.2-0
main: com.PyrexNetwork.KothTokenPlugin
api-version: 1.18
commands:
  kothtoken:
    description: Main command for KothToken plugin
    usage: /kothtoken <subcommand>
    permission: kothtoken.use
    aliases: [kt]
permissions:
  kothtoken.use:
    description: Allows the use of the KothToken command
    default: true
  kothtoken.admin.reload:
    description: Allows reloading the KothToken plugin
    default: op
  kothtoken.admin.manage:
    description: Allows managing tokens of other players
    default: op