name: PyrexTokens
main: com.PyrexNetwork.PyrexTokenPlugin
version: v1.2-5
api-version: 1.18
commands:
  pyrextoken:
    description: Main command for PyrexTokens
    usage: /<command>
    permission: pyrextoken.use
    permission-message: You do not have permission to use this command.
    aliases: [pt, ptoken, pyrext]
permissions:
  pyrextoken.use:
    description: Allows the use of the KothToken command
    default: true
  pyrextoken.admin.reload:
    description: Allows reloading the KothToken plugin
    default: op
  pyrextoken.admin.manage:
    description: Allows managing tokens of other players
    default: op